core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('teacher.urls')),

]

teacher/models.py
from django.db import models
from django.utils import timezone
from dateutil.relativedelta import relativedelta
import datetime

class Group(models.Model):
    name = models.CharField(max_length=39)

    def __str__(self):
        return self.name

class LessonSchedule(models.Model):
    group = models.ForeignKey(Group, related_name='schedules', on_delete=models.CASCADE)
    start_date = models.DateField(default=timezone.now)
    end_date = models.DateField(null=True)
    time = models.TimeField(default=datetime.time(12, 0))

    DAYS_OF_WEEK = (
        ('Bazar Ertəsi', 'Bazar Ertəsi'),
        ('Çərşənbə Axşamı', 'Çərşənbə Axşamı'),
        ('Çərşənbə', 'Çərşənbə'),
        ('Cümə Axşamı', 'Cümə Axşamı'),
        ('Cümə', 'Cümə'),
        ('Şənbə', 'Şənbə'),
        ('Bazar', 'Bazar'),
    )
    day_of_week = models.CharField(max_length=30, choices=DAYS_OF_WEEK, null=True)

class Student(models.Model):
    group = models.ForeignKey('Group', on_delete=models.CASCADE)
    full_name = models.CharField(max_length=38)
    price = models.IntegerField()
    grade = models.IntegerField()
    add_date = models.DateField(default=timezone.now)
    end_date = models.DateField()
    student_mobile = models.CharField(max_length=15, null=True, blank=True)
    parent_mobile = models.CharField(max_length=15, null=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.end_date:
            self.end_date = self.add_date + relativedelta(months=1)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.full_name

teacher/forms.py
from django import forms
from .models import Group, Student, LessonSchedule
from datetime import datetime, date

class CustomDateInput(forms.DateInput):
    input_type = 'text'
    format = '%d/%m/%Y'

    def __init__(self, *args, **kwargs):
        kwargs['format'] = self.format
        super().__init__(*args, **kwargs)

    def format_value(self, value):
        if value:
            if isinstance(value, (datetime, date)):
                return value.strftime(self.format)
        return value

class StudentForm(forms.ModelForm):
    add_date = forms.CharField(widget=CustomDateInput(attrs={'class': 'form-control', 'placeholder': 'DD/MM/YYYY'}))
    student_mobile = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'form-control', 'maxlength': '17', 'placeholder': '(0XX) XXX XX XX'}))
    parent_mobile = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'form-control', 'maxlength': '18', 'placeholder': '(0XX) XXX XX XX'}))

    class Meta:
        model = Student
        fields = ['group', 'full_name', 'price', 'grade', 'add_date', 'student_mobile', 'parent_mobile']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if not self.instance.pk:  # If creating a new form
            self.fields['add_date'].initial = date.today().strftime('%d/%m/%Y')

    def clean_add_date(self):
        add_date = self.cleaned_data['add_date']
        try:
            return datetime.strptime(add_date, '%d/%m/%Y').date()
        except ValueError:
            raise forms.ValidationError("Tarixi DD/MM/YYYY formatında daxil edin.")

class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['name',]

class LessonScheduleForm(forms.ModelForm):
    class Meta:
        model = LessonSchedule
        fields = ['day_of_week', 'time']
        labels = {
            'day_of_week': 'Həftənin Günü',
            'time': 'Saat',
        }
        widgets = {
            'day_of_week': forms.Select(attrs={'class': 'form-control'}),
            'time': forms.TimeInput(format='%H:%M'),
        }

templates/student/add_student.html
{% include "index.html" %}

{% block content %}
<style>
    form {
        max-width: 400px;
        margin: 0 auto;
        padding: 20px;
        background: #f9f9f9;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    input[type="text"],
    input[type="email"],
    input[type="number"],
    select {
        width: 100%;
        padding: 10px;
        margin: 5px 0;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-sizing: border-box;
    }

    button[type="submit"] {
        background-color: #4CAF50;
        color: white;
        padding: 12px 20px;
        margin: 8px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        width: 100%;
    }

    button[type="submit"]:hover {
        background-color: #45a049;
    }

    .group-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 20px;
    }

    .group-header h1 {
        font-size: 30px;
        margin: 0 auto;
        text-align: center;
        flex-grow: 1;
    }

    .back-button {
        background-color: #424448;
        color: white;
        padding: 5px 10px;
        border: none;
        border-radius: 10px;
        text-decoration: none;
        font-size: 14px;
    }

    .back-button:hover {
        background-color: #000000;
        text-decoration: none;
        color: white;
    }

    #addd{
        font-size: large;
    }
</style>

{% if messages %}
<div class="alert alert-success" role="alert">
    {% for message in messages %}
    {{ message }}
    {% endfor %}
</div>
{% endif %}

<br>
<form method="post" autocomplete="off">
    <div class="group-header">
        <a class="back-button" href="{% url 'group_list' %}">Geri</a>
        <h1>Tələbə Əlavə Et</h1>
    </div>
    {% csrf_token %}
    <div class="form-group">
        <label for="id_group">Qrup:</label>
        {{ form.group }}
    </div>
    <div class="form-group">
        <label for="id_full_name">Ad-Soyad:</label>
        {{ form.full_name }}
    </div>
    <div class="form-group">
        <label for="id_student_fee">Sinif:</label>
        {{ form.grade }}
    </div>
    <div class="form-group">
        <label for="id_student_mobile">Tələbənin Nömrəsi:</label>
        {{ form.student_mobile }}
    </div>
    <div class="form-group">
        <label for="id_parent_mobile">Valideynin Nömrəsi:</label>
        {{ form.parent_mobile }}
    </div>
    <div class="form-group">
        <label for="id_monthly_fee">Ödəniş:</label>
        {{ form.price }}
    </div>
    <div class="form-group">
        <label for="id_registration_date">Qeydiyyat tarixi:</label>
        {{ form.add_date }}
    </div>
    <button type="submit" id="addd">Əlavə Et</button>
</form>
<br><br>

<script>
    function maskPhoneNumber(input) {
        input.addEventListener('input', function (e) {
            let value = e.target.value.replace(/\D/g, '');  // Remove all non-digit characters

            // Ensure the value starts with '0' if it's not already there
            if (!value.startsWith('0')) {
                value = '0' + value;
            }

            // Apply the formatting
            let x = value.match(/(\d{0,3})(\d{0,3})(\d{0,2})(\d{0,2})/);
            e.target.value = (x[1] ? `(${x[1]})` : '') +
                (x[2] ? ` ${x[2]}` : '') +
                (x[3] ? ` ${x[3]}` : '') +
                (x[4] ? ` ${x[4]}` : '');
        });
    }

    document.addEventListener('DOMContentLoaded', function () {
        let studentMobileInput = document.getElementById('id_student_mobile');
        let parentMobileInput = document.getElementById('id_parent_mobile');

        if (studentMobileInput) {
            studentMobileInput.placeholder = "(0XX) XXX XX XX";
            maskPhoneNumber(studentMobileInput);
        }
        if (parentMobileInput) {
            parentMobileInput.placeholder = "(0XX) XXX XX XX";
            maskPhoneNumber(parentMobileInput);
        }
    });
</script>


<br><br>
{% endblock content %}

templates/student/pay_day.html
{% extends "index.html" %}

{% block content %}
<title>Pay Day</title>

<style>
    .pay-day-container {
        max-width: 1300px;
        margin: 0 auto;
        padding: 20px;
        background: #f9f9f9;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    .pay-day-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 20px;
    }

    .pay-day-header h1 {
        font-size: 24px;
        margin: 0 auto;
        text-align: center;
        flex-grow: 1;
        font-weight: bold;
    }

    .back-button {
        background-color: #424448;
        color: white;
        padding: 5px 10px;
        border: none;
        border-radius: 10px;
        text-decoration: none;
        font-size: 14px;
    }

    .back-button:hover {
        background-color: #000000;
        text-decoration: none;
        color: white;
    }
    
    table {
        width: 100%;
        border-collapse: collapse;
        margin-bottom: 20px;
    }

    table, th, td {
        border: 1px solid #ddd;
    }

    th, td {
        padding: 10px;
        text-align: left;
    }

    th {
        background-color: #f2f2f2;
    }

    tr:nth-child(even) {
        background-color: #f9f9f9;
    }

    tr:hover {
        background-color: #f1f1f1;
    }

    .btn-group {
        display: flex;
        gap: 5px;
    }

    .btn {
        padding: 5px 10px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        text-decoration: none;
    }

    /* Add these styles for text truncation */
    .truncated {
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
        max-width: 150px; /* Adjust as needed */
    }

    .link-style {
        text-decoration: none;
        color: black;
        font-weight: bold;
    }

    .link-style:hover {
        text-decoration: none; /* or any other hover effect you prefer */
        color: gray; /* or any other color you prefer */
    }
</style>

<div class="container pay-day-container mt-5">
    <div class="pay-day-header">
        <a class="back-button" href="{% url 'group_list' %}">Geri</a>
        <h1>Ödəniş</h1>
    </div>
    <table class="table text-center">
        <thead>
            <tr>
                <th class="text-center">#</th>
                <th class="text-center">Ad-Soyad</th>
                <th class="text-center">Qrup</th>
                <th class="text-center">Sinif</th>
                <th class="text-center">Qiymət</th>
                <th class="text-center">Nömrə</th>
                <th class="text-center">Başlanğıc Tarixi</th>
                <th class="text-center">Bitiş Tarixi</th>
                <th class="text-center">Əməliyyatlar</th>
            </tr>
        </thead>
        <tbody>
            {% for student in expired_students %}
                <tr>
                    <td class="text-center">{{ forloop.counter }}</td>
                    <td class="text-center">{{ student.full_name }}</td>
                    <td class="truncated" title="{{ student.group.name }}">
                        <a href="{% url 'group_detail' student.group.id %}?next=pay_day" class="link-style">
                            {{ student.group.name|truncatechars:20 }}
                        </a>
                    </td>
                    <td class="text-center">{{ student.grade }}</td>
                    <td class="text-center">{{ student.price }} ₼</td>
                    <td class="text-center">
                    {% if student.student_mobile != '(0)' and student.student_mobile %}
                        Ş-{{ student.student_mobile }} <br>
                    {% endif %}
                    {% if student.parent_mobile != '(0)' and student.parent_mobile %}
                        V-{{ student.parent_mobile }}
                    {% endif %}
                    </td>
                    <td class="text-center">{{ student.add_date|date:"d/m/Y" }}</td>
                    <td class="text-center">{{ student.end_date|date:"d/m/Y" }}</td>
                    <td class="text-center">
                        <a href="{% url 'renew_student' student.pk %}" class="btn btn-sm btn-success" onclick="return confirm('Bu tələbəni yeniləmək istədiyinizə əminsiniz?')">Yenilə</a>
                        <a href="{% url 'update_student_pay' student.id %}" class="btn btn-sm btn-warning">Düzəliş Et</a>
                        <a href="{% url 'delete_student_pay' student.id %}" class="btn btn-sm btn-danger" onclick="return confirm('Bu tələbəni silmək istədiyinizə əminsiniz?')">Sil</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<br><br><br>
{% endblock content %}

templates/student/update_student.html
{% include "index.html" %}

{% block content %}
<style>
    form {
        max-width: 400px;
        margin: 0 auto;
        padding: 20px;
        background: #f9f9f9;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    input[type="text"],
    input[type="email"],
    input[type="number"],
    select {
        width: 100%;
        padding: 10px;
        margin: 5px 0;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-sizing: border-box;
    }

    button[type="submit"] {
        background-color: #4CAF50;
        color: white;
        padding: 12px 20px;
        margin: 8px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        width: 100%;
    }

    button[type="submit"]:hover {
        background-color: #45a049;
    }

    .group-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 20px;
    }

    .group-header h1 {
        font-size: 30px;
        margin: 0 auto;
        text-align: center;
        flex-grow: 1;
    }

    .back-button {
        background-color: #424448;
        color: white;
        padding: 5px 10px;
        border: none;
        border-radius: 10px;
        text-decoration: none;
        font-size: 14px;
    }

    .back-button:hover {
        background-color: #000000;
        text-decoration: none;
        color: white;
    }
</style>

{% if messages %}
<div class="alert alert-success" role="alert">
    {% for message in messages %}
    {{ message }}
    {% endfor %}
</div>
{% endif %}

<br>
<form method="post" autocomplete="off">
    <div class="group-header">
        <a class="back-button" href="{% url 'group_detail' group.id %}">Geri</a>
        <h1>Tələbəyə Düzəliş Et</h1>
    </div>
    {% csrf_token %}
    <div class="form-group">
        <label for="id_group">Qrup:</label>
        {{ form.group }}
    </div>
    <div class="form-group">
        <label for="id_full_name">Ad-Soyad:</label>
        {{ form.full_name }}
    </div>
    <div class="form-group">
        <label for="id_student_fee">Sinif:</label>
        {{ form.grade }}
    </div>
    <div class="form-group">
        <label for="id_student_mobile">Tələbənin Nömrəsi:</label>
        {{ form.student_mobile }}
    </div>
    <div class="form-group">
        <label for="id_parent_mobile">Valideynin Nömrəsi:</label>
        {{ form.parent_mobile }}
    </div>
    <div class="form-group">
        <label for="id_monthly_fee">Ödəniş:</label>
        {{ form.price }}
    </div>
    <div class="form-group">
        <label for="id_registration_date">Başlanğıc tarixi:</label>
        {{ form.add_date }}
    </div>
    <button type="submit">Düzəliş Et</button>
</form>
<br><br>

<script>
    function maskPhoneNumber(input) {
        input.addEventListener('input', function (e) {
            let value = e.target.value.replace(/\D/g, '');  // Remove all non-digit characters

            // Ensure the value starts with '0' if it's not already there
            if (!value.startsWith('0')) {
                value = '0' + value;
            }

            // Apply the formatting
            let x = value.match(/(\d{0,3})(\d{0,3})(\d{0,2})(\d{0,2})/);
            e.target.value = (x[1] ? `(${x[1]})` : '') +
                (x[2] ? ` ${x[2]}` : '') +
                (x[3] ? ` ${x[3]}` : '') +
                (x[4] ? ` ${x[4]}` : '');
        });
    }

    document.addEventListener('DOMContentLoaded', function () {
        let studentMobileInput = document.getElementById('id_student_mobile');
        let parentMobileInput = document.getElementById('id_parent_mobile');

        if (studentMobileInput) {
            studentMobileInput.placeholder = "(0XX) XXX XX XX";
            maskPhoneNumber(studentMobileInput);
        }
        if (parentMobileInput) {
            parentMobileInput.placeholder = "(0XX) XXX XX XX";
            maskPhoneNumber(parentMobileInput);
        }
    });
</script>

<br><br>
{% endblock content %}

templates/student/update_student_pay.html
{% include "index.html" %}

{% block content %}
<style>
    form {
        max-width: 400px;
        margin: 0 auto;
        padding: 20px;
        background: #f9f9f9;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    input[type="text"],
    input[type="email"],
    input[type="number"],
    select {
        width: 100%;
        padding: 10px;
        margin: 5px 0;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-sizing: border-box;
    }

    button[type="submit"] {
        background-color: #4CAF50;
        color: white;
        padding: 12px 20px;
        margin: 8px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        width: 100%;
    }

    button[type="submit"]:hover {
        background-color: #45a049;
    }

    .group-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 20px;
    }

    .group-header h1 {
        font-size: 30px;
        margin: 0 auto;
        text-align: center;
        flex-grow: 1;
    }

    .back-button {
        background-color: #424448;
        color: white;
        padding: 5px 10px;
        border: none;
        border-radius: 10px;
        text-decoration: none;
        font-size: 14px;
    }

    .back-button:hover {
        background-color: #000000;
        text-decoration: none;
        color: white;
    }
</style>

{% if messages %}
<div class="alert alert-success" role="alert">
    {% for message in messages %}
    {{ message }}
    {% endfor %}
</div>
{% endif %}

<br>
<form method="post" autocomplete="off">
    <div class="group-header">
        <a class="back-button" href="{% url 'pay_day' %}">Geri</a>
        <h1>Tələbəyə Düzəliş Et</h1>
    </div>
    {% csrf_token %}
    <div class="form-group">
        <label for="id_group">Qrup:</label>
        {{ form.group }}
    </div>
    <div class="form-group">
        <label for="id_full_name">Ad-Soyad:</label>
        {{ form.full_name }}
    </div>
    <div class="form-group">
        <label for="id_student_fee">Sinif:</label>
        {{ form.grade }}
    </div>
    <div class="form-group">
        <label for="id_student_mobile">Tələbənin Nömrəsi:</label>
        {{ form.student_mobile }}
    </div>
    <div class="form-group">
        <label for="id_parent_mobile">Valideynin Nömrəsi:</label>
        {{ form.parent_mobile }}
    </div>
    <div class="form-group">
        <label for="id_monthly_fee">Ödəniş:</label>
        {{ form.price }}
    </div>
    <div class="form-group">
        <label for="id_registration_date">Başlanğıc tarixi:</label>
        {{ form.add_date }}
    </div>
    <button type="submit">Düzəliş Et</button>
</form>
<br><br>

<script>
    function maskPhoneNumber(input) {
        input.addEventListener('input', function (e) {
            let value = e.target.value.replace(/\D/g, '');  // Remove all non-digit characters

            // Ensure the value starts with '0' if it's not already there
            if (!value.startsWith('0')) {
                value = '0' + value;
            }

            // Apply the formatting
            let x = value.match(/(\d{0,3})(\d{0,3})(\d{0,2})(\d{0,2})/);
            e.target.value = (x[1] ? `(${x[1]})` : '') +
                (x[2] ? ` ${x[2]}` : '') +
                (x[3] ? ` ${x[3]}` : '') +
                (x[4] ? ` ${x[4]}` : '');
        });
    }

    document.addEventListener('DOMContentLoaded', function () {
        let studentMobileInput = document.getElementById('id_student_mobile');
        let parentMobileInput = document.getElementById('id_parent_mobile');

        if (studentMobileInput) {
            studentMobileInput.placeholder = "(0XX) XXX XX XX";
            maskPhoneNumber(studentMobileInput);
        }
        if (parentMobileInput) {
            parentMobileInput.placeholder = "(0XX) XXX XX XX";
            maskPhoneNumber(parentMobileInput);
        }
    });
</script>

<br><br>
{% endblock content %}